services:
  backend:
    build: .
    container_name: flipkart-backend

    ports:
      - "8000:8000"

    env_file:
      - .env.docker

    volumes:
      - ./data/uploads/validations:/app/data/uploads/validations

    depends_on:
      - postgres


  postgres:
    image: postgres:17

    container_name: flipkart-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flipkart

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4

    container_name: flipkart-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - postgres

volumes:
  postgres_data: